import { test, expect } from "@playwright/test";

const validBrief = {
  id: "b1",
  title: "Weekly Care Brief",
  content: {
    recipient_name: "Margaret",
    dob: null,
    generated_at: "2026-04-13T10:00:00Z",
    medications: [
      { drug_name: "Lisinopril", dosage: "10mg", instructions: "once daily" },
    ],
    recent_entries: [
      {
        occurred_at: "2026-04-12T08:00:00Z",
        text: "Good morning",
        mood: "good",
        flagged: false,
      },
    ],
  },
  includes: ["medications", "journal"],
  created_at: "2026-04-13T10:00:00Z",
};

test.describe("Care Brief public page", () => {
  test("invalid token shows error", async ({ page }) => {
    await page.route("**/api/brief/invalid-tok", async (route) => {
      await route.fulfill({
        status: 404,
        contentType: "application/json",
        body: JSON.stringify({
          error: "This care brief is no longer available.",
        }),
      });
    });
    await page.goto("/brief/invalid-tok");
    // TD-71: empty state was rebranded to "This care brief link has expired
    // or been revoked." Match either the new copy or the legacy phrasings so
    // a future copy tweak doesn't tank the suite again.
    await expect(
      page.getByText(
        /expired or been revoked|no longer available|Unable to load/i,
      ),
    ).toBeVisible({ timeout: 10000 });
  });

  test("valid token shows brief title and recipient", async ({ page }) => {
    await page.route("**/api/brief/valid-tok", async (route) => {
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(validBrief),
      });
    });
    await page.goto("/brief/valid-tok");
    await expect(page.getByText("Weekly Care Brief")).toBeVisible({
      timeout: 10000,
    });
    await expect(page.getByText("Margaret")).toBeVisible({ timeout: 10000 });
  });

  test("valid brief shows CareSync footer", async ({ page }) => {
    await page.route("**/api/brief/valid-tok", async (route) => {
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(validBrief),
      });
    });
    await page.goto("/brief/valid-tok");
    await expect(
      page.getByText("This is a point-in-time snapshot generated by CareSync."),
    ).toBeVisible({ timeout: 10000 });
  });
});
